# -*- coding: utf-8 -*-
"""Rick and Morty APIs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BAzA1TT4FQJF7tFwlAhsl1M9jAl6IB8N
"""

import requests
url = "https://rickandmortyapi.com/api"
endpoint = "/character"
response = requests.get(url + endpoint) # Because they are strings
data = response.json()

# initial_request(url,endpoint)
def initial_request(url,endpoint,x):
    response = requests.get(url + endpoint+f'?page={x}') # Because they are strings
    return response.json()

def get_pages(response):
  return response['info']['pages']

# dfunction to lopp through the items
def parser_json(response):
  character_list = []
  for item in response['results']:
    char={
      'name': item['name'],
      'episodes':len(item['episode'])
    }
    character_list.append(char)
    print(item['name'],item['episode'])
    return character_list

# Pagination
key_list=[]
for x in range(1,get_pages(data)+1):
  data=initial_request(url,endpoint,x)
  key_list.extend(parser_json(data))

# Convert the result to a datafram
import pandas as pd
pd.DataFrame(key_list).head()

